# Generated by Django 4.2.6 on 2024-11-26 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app01", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userinfo",
            name="create_time",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Create Time"),
        ),
    ]
