# Generated by Django 4.2.6 on 2024-11-27 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app01", "0002_alter_userinfo_create_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="spareparts",
            name="other",
            field=models.CharField(
                blank=True, max_length=128, null=True, verbose_name="Other"
            ),
        ),
    ]
