# Generated by Django 4.2.6 on 2024-11-27 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app01", "0003_spareparts_other"),
    ]

    operations = [
        migrations.AddField(
            model_name="spareparts",
            name="last_edit",
            field=models.DateTimeField(auto_now=True, verbose_name="Last Edit Time"),
        ),
    ]
