# Generated by Django 4.2.6 on 2024-12-04 04:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app01", "0006_alter_trade_other"),
    ]

    operations = [
        migrations.AddField(
            model_name="trade",
            name="created_by",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="app01.userinfo",
                verbose_name="Created By",
            ),
        ),
    ]
