# Generated by Django 4.2.6 on 2024-12-05 00:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app01", "0007_trade_created_by"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trade",
            name="spareparts_id",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="app01.spareparts",
                verbose_name="Spare Part",
            ),
        ),
        migrations.AlterField(
            model_name="userinfo",
            name="depart_id",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="app01.department",
                verbose_name="Department",
            ),
        ),
    ]
