# Generated by Django 4.2.6 on 2024-12-05 00:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app01", "0009_alter_trade_created_by_userinfoedit_sparepartsedit"),
    ]

    operations = [
        migrations.CreateModel(
            name="EditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "old_info",
                    models.CharField(
                        blank=True, max_length=512, null=True, verbose_name="Old Info"
                    ),
                ),
                ("new_info", models.CharField(max_length=512, verbose_name="New Info")),
                (
                    "edit_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="Trade Time"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="app01.userinfo",
                        verbose_name="Created By",
                    ),
                ),
            ],
        ),
        migrations.RemoveField(model_name="userinfoedit", name="created_by",),
        migrations.RemoveField(model_name="userinfoedit", name="userinfo_id",),
        migrations.DeleteModel(name="SparepartsEdit",),
        migrations.DeleteModel(name="UserInfoEdit",),
    ]
