# Generated by Django 4.2.6 on 2024-12-05 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app01", "0010_editlog_remove_userinfoedit_created_by_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="editlog",
            name="new_info",
            field=models.CharField(
                blank=True, max_length=512, null=True, verbose_name="New Info"
            ),
        ),
    ]
